AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Backend API para portal de usuarios Tappy - Gestión de usuarios con DynamoDB"

Parameters:
  Stage:
    Type: String
    Default: Prod
  JwtSecret:
    Type: String
    NoEcho: true
    Description: "JWT secret used by the application"
  UserTableName:
    Type: String
    Description: "DynamoDB Table Name for Users"
  OrdersTableName:
    Type: String
    Description: "DynamoDB Table Name for Orders"
  PaymentsTableName:
    Type: String
    Description: "DynamoDB Table Name for Payments"

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 512


Resources:
  TappyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - Authorization
          - x-auth-token
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS

  TappyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "TappyApiFunction-${Stage}"
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      MemorySize: 512
      Timeout: 30
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:DescribeTable
                - dynamodb:ListTables
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${UserTableName}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${UserTableName}/index/*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${OrdersTableName}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${OrdersTableName}/index/*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${PaymentsTableName}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${PaymentsTableName}/index/*"
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Environment:
        Variables:
          JWT_SECRET: !Ref JwtSecret
          TABLE_NAME: !Ref UserTableName
          ORDERS_TABLE: !Ref OrdersTableName
          PAYMENTS_TABLE: !Ref PaymentsTableName
      Events:
        ApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref TappyHttpApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${TappyHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
