AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Backend API para portal de usuarios Tappy - Gestión de usuarios con DynamoDB"

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 512
  Api:
    Cors:
      # Explicit CORS config so API Gateway includes required headers in OPTIONS preflight
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-Type,Authorization,x-auth-token'"
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      # AllowCredentials could be added if later you restrict origin and need cookies
      # AllowCredentials: true

Parameters:
  JwtSecret:
    Type: String
    NoEcho: true
    Description: "JWT secret used by the application (will not be echoed in CLI)"

Resources:

  TappyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TappyApiFunction
      CodeUri: .
      Handler: server/lambda.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 30
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:DescribeTable
                - dynamodb:ListTables
              Resource:
                - arn:aws:dynamodb:us-east-1:837563945297:table/Tappy_Users
                - arn:aws:dynamodb:us-east-1:837563945297:table/Tappy_Users/index/*
                - arn:aws:dynamodb:us-east-1:837563945297:table/Tappy_Orders
                - arn:aws:dynamodb:us-east-1:837563945297:table/Tappy_Orders/index/*
                - arn:aws:dynamodb:us-east-1:837563945297:table/Tappy_Payments
                - arn:aws:dynamodb:us-east-1:837563945297:table/Tappy_Payments/index/*
      Environment:
        Variables:
          JWT_SECRET: !Ref JwtSecret
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL para el portal de usuarios"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  
  UserTableName:
    Description: "Nombre de la tabla DynamoDB de usuarios"
    Value: "Tappy_Users"
    Export:
      Name: !Sub "${AWS::StackName}-UserTableName"
  
  OrdersTableName:
    Description: "Nombre de la tabla DynamoDB de órdenes"
    Value: "Tappy_Orders"
    Export:
      Name: !Sub "${AWS::StackName}-OrdersTableName"
  
  PaymentsTableName:
    Description: "Nombre de la tabla DynamoDB de pagos"
    Value: "Tappy_Payments"
    Export:
      Name: !Sub "${AWS::StackName}-PaymentsTableName"
