name: Deploy Backend (SAM)

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

permissions:
  id-token: write   # OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      STACK_NAME: tappy-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: |
            server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-

      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ${{ env.AWS_REGION }}
            role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
            role-session-name: GitHubActionsDeploy

      - name: SAM Build
        working-directory: server
        run: sam build --use-container

      - name: SAM Deploy
        working-directory: server
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          sam deploy \
            --stack-name $STACK_NAME \
            --no-confirm-changeset \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides JwtSecret=$JWT_SECRET \
            --resolve-s3

      - name: Show API URL
        working-directory: server
        run: |
          aws cloudformation describe-stacks --stack-name $STACK_NAME \
            --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' --output text || true

      - name: Save API URL as artifact
        working-directory: server
        run: |
          aws cloudformation describe-stacks --stack-name $STACK_NAME \
            --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' --output text > api-url.txt

      - name: Upload API URL artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-url
          path: server/api-url.txt
